---
title: "Desarrollo"
author: "Alejandro Brenes, Santiago Fernández, Eyeri Méndez y Erick Venegas"
date: "`r Sys.Date()`"
output: html_document
---

Se inicia cargando las librerías necesarias.

```{r librerias}
pacman::p_load(dplyr,
               ggplot2,
               jsonlite,
               lubridate
               )
```

Se procede a cargar los datos.

```{r carga_datos}
eventos_EEUU <- fromJSON("data/Eventos EEUU.json")[[2]]
```

Algunas correcciones de formato.

```{r correccion_formato}
# Formato de la fecha
eventos_EEUU$begDate <-
  as.Date(as.character(eventos_EEUU$begDate), format = "%Y%m%d")
eventos_EEUU$endDate <-
  as.Date(as.character(eventos_EEUU$endDate), format = "%Y%m%d")

# Nombre de las columnas (coste en millones de dólares y coste ajustado al 2024)
colnames(eventos_EEUU) <-
  c(
    "nombre",
    "desastre",
    "inicio",
    "final",
    "coste_ajustado",
    "coste_original",
    "muertes"
  )

# Columna de duración del desastre (en días)
eventos_EEUU <- eventos_EEUU %>%
  mutate(duracion = as.integer(final - inicio))
```

Se agrega la variable de estación climatológica.

```{r estacion}
eventos_EEUU <- eventos_EEUU %>%
  mutate(
    estacion = case_when(
      month(inicio) %in% c(12, 1, 2) ~ "Invierno",
      month(inicio) %in% c(3, 4, 5)  ~ "Primavera",
      month(inicio) %in% c(6, 7, 8)  ~ "Verano",
      month(inicio) %in% c(9, 10, 11) ~ "Otoño"
    )
  )
```

